### ISSUE TITLE
Cannot use the ropenblas() function

### ISSUE THREAD

**Issue by waynelapierre** [prdm0/ropenblas#11]
I am running the ropenblas() function on R 3.6.2 on a Fedora 31 machine. When I entered my root password for the first time I got the error message: shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory.

**Comment by prdm0** [comment]
It will be fixed soon. To make it work, run: `ropenblas("0.3.9 ")`.

**Comment by prdm0** [comment]
The error was in the tag of the latest version of the OpenBLAS library. All tags have a pattern in the form `v{version_number}` (without the `{` symbol). Apparently everything is correct now.

**Comment by prdm0** [comment]
Try again and let me know if the problem persists. It is not necessary to install the package again.

**Comment by waynelapierre** [comment]
when I used ropenblas("0.3.9"), it worked. When I used ropenblas(), I still got the error

**Comment by prdm0** [comment]
Strange, could you detail the error better? Here it works.
