### ISSUE TITLE
Error in updating to 0.2.3

### ISSUE THREAD

**Issue by Procyon-Lotor-Hub** [prdm0/ropenblas#15]
Hiya, i am getting the follow error when trying to upgrade from 0.2.2 to the newest version:

* installing *source* package ‘ropenblas’ ...
** package ‘ropenblas’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/user/R/x86_64-pc-linux-gnu-library/3.6/git2r/libs/git2r.so':
  libgit2.so.28: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘ropenblas’
* removing ‘/home/user/R/x86_64-pc-linux-gnu-library/3.6/ropenblas’
* restoring previous ‘/home/user/R/x86_64-pc-linux-gnu-library/3.6/ropenblas’
Warning in install.packages :
  installation of package ‘ropenblas’ had non-zero exit status

**Comment by prdm0** [comment]
There was no problem here. However, see if it resolves:

```{r}
install.packages("git2r")
install.packages("ropenblas")
```

**Comment by Procyon-Lotor-Hub** [comment]
> There was no problem here. However, see if it resolves:
> 
> ```
> install.packages("git2r")
> install.packages("ropenblas")
> ```

That did the trick. Thanks for the prompt response.
