### ISSUE TITLE
Workflow suggestions

### ISSUE THREAD

**Issue by llrs** [prdm0/ropenblas#16]
Many thanks for this package! It worked nicely.

I'm using for the first time this package and I found surprising that after asking for the user password then it shows what are the system dependencies. I think it would be easier for the user if it would be in the opposite order. First the requirements and then ask for the password to proceed. 

```
Enter your ROOT OS password (attempt 1 of 5):


You must be the system administrator. You must install the following dependencies on your operating system (Linux):

      1 - Make: GNU Make utility to maintain groups of programs;
      2 - GNU GCC: The GNU Compiler Collection - C frontends;
      3 - GNU GCC Fortran: The GNU Compiler Collection - Fortran frontends.

```
Also I got asked three times for my password. This is great so the program doesn't store it, but could it be reduced to just once?

Also after ending it restarted an R session but ignored the session it was called on (I have both 3.6.3 and 4.0.0 versions and installed OpenBlas on the 4.0.0 but I got this message:

```
Enter your ROOT OS password (attempt 1 of 5): 
WARNING: ignoring environment value of R_HOME

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

Many thanks for maintaining the package!

**Comment by prdm0** [comment]
I'm working on it asking for the password only once. I am also making changes so that R is installed in a local directory and not in `/ opt`. I will remove the messages of  dependencies, since the package already identifies if any dependencies and inform the user what to install in the operating system.

**Comment by llrs** [comment]
Great thanks for working on this! I'm not sure that I understood the reference about installing R on local directory. Why do it need to reinstall R ? Shouldn't it be enough to use the current installed R? Probably I don't understand how ropenblas works well enough so don't feel compelled to answer.

**Comment by prdm0** [comment]
Prezado @llrs  if your interest is just to link the OpenBLAS library to R there is no need to compile R for this purpose. For this case, use only the `ropenblas()` function. If you want to install and link an older version of OpenBLAS you can, however after receiving a notice that there is already a link to a newer version of OpenBLAS. If you are using an older version of OpenBLAS and you are running the `ropenblas()` function without an argument, it will understand that you are wanting to install and compile the latest version of the OpenBLAS library. In situations where you are already using the latest version of OpenBLAS that was compiled and installed by the `ropenblas()` function, it will inform you that you are already up to date with the current version. However, if you still want to recompile, you can too.

If you are interested in using a different version of R and at the same time linking with the OpenBLAS library, the `rcompiler()` function can be used by specifying the R language version and the OpenBLAS library version.

Suppose you have run `rcompiler()` and then `rcompiler(x = "3.6.3")`, so for the present date, you will have **4.0.0** and **3.63** on your on your system, respectively. So suppose you, for some reason, needed to go to version **3.6.2** of R, that is, you ran the `rcompiler(x = "3.6.2")` code. If, later on, the desire to go to version **4.0.0** the `rcompiler()` function will allow you to go without having to compile R again.

I am trying, as far as possible, to implement functions that avoid unnecessary compilations. The next version will also bring improvements in terms of not having to enter the ROOT password several times. Only once will be necessary for each of the functions exported by the package.

**Comment by llrs** [comment]
Great, many thanks for explaining it. Now I understand more what this package can do. Very useful!

**Comment by prdm0** [comment]
Dear @llrs, version **0.2.5** of **ropenblas** is on CRAN. Now it's easier and more fun to use. The site documentation has also been improved. Best regards.

**Comment by llrs** [comment]
Thanks for letting me know
