### ISSUE TITLE
could not find function "col_green"

### ISSUE THREAD

**Issue by waynelapierre** [prdm0/ropenblas#18]
After running `ropenblas(x = "0.3.10")`, I got this: 
```
═══════════════ Procedure Completed ══════════════
Error in col_green(symbol$tick) : could not find function "col_green"
```

My operating system is Fedora 32 and my R version is 4.0.2.

**Comment by prdm0** [comment]
Thanks for the feedback. It has been fixed and version 0.2.8 has already been submitted to CRAN yesterday. It should soon be available in the official repositories. However, you can already find it on github:

```
remotes::install_github("prdm0/ropenblas")
```

Best regards,
@prdm0

**Comment by prdm0** [comment]
This topic will remain open until version 0.2.8 of the ropenblas package will be on [CRAN](https://cran.r-project.org/web/packages/index.html).

**Comment by prdm0** [comment]
Version 0.2.8 is already in CRAN and the bug has been fixed.
