### ISSUE TITLE
Fedora 33 will use OpenBlas as default 

### ISSUE THREAD

**Issue by waynelapierre** [prdm0/ropenblas#19]
Fedora 33 OS will use OpenBlas as the default system-wide library for all applications that depends on it. See this accepted change: https://fedoraproject.org/wiki/Changes/FlexiBLAS_as_BLAS/LAPACK_manager

This might make your ropenblas package less important. I highly appreciate your effort in this great package, but it would be great to have something similar to ropenblas that links R to MKL.

**Comment by prdm0** [comment]
See that there are a multitude of linux distributions. In addition, the idea of the ropenblas package is to allow that in distributions where recent versions of R are not available, users can install and switch between versions of R independently of the distribution repositories.

For example, I use Arch and Gentoo. Distributions like these or distributions like Debian or any other that take some time to have the repositories updated with recent versions of R, users have difficulties installing the latest version of R.

That way, I don't feel any threat to Fedora using the OpenBLAS library by default. In RStudio you have to pay to be able to switch between versions of R and here you can do it easily. If for some reason you are interested in switching between versions of OpenBLAS you can too.
