### ISSUE TITLE
ropenblas(x = "0.3.12") is error

### ISSUE THREAD

**Issue by statli** [prdm0/ropenblas#22]
Hi sir,

> When I run ropenblas(x = "0.3.12"), it return a error message "Error in sudo_key() : Sorry. Apparently you don't is the administrator of the operating system. You missed all three attempts."

> I am sure I am the administrator and sudo password is right.

**Comment by prdm0** [comment]
Note that there were more than 8 thousand downloads of the package. This suggestion of a problem is very strange. What it seems to me is that you are a user who is added to sudoers but you are not the main user of the system. In the bash shell can you use the `su` command? Is there an administrator on the system? Which GNU / Linux distribution do you use?

**Comment by statli** [comment]
> Note that there were more than 8 thousand downloads of the package. This suggestion of a problem is very strange. What it seems to me is that you are a user who is added to sudoers but you are not the main user of the system. In the bash shell can you use the `su` command? Is there an administrator on the system? Which GNU / Linux distribution do you use?

I am run it in CentOS6.8/CentOS7 and I am the administrator. I delete my name from sudo, and I try it in root name or my name, it is a same error.
Thank you, sir. I will try it.
