### ISSUE TITLE
ropenblas(x="0.3.13") error

### ISSUE THREAD

**Issue by sabato96** [prdm0/ropenblas#26]
Error in sudo_key() : 
Sorry. Apparently you don't is the administrator of the operating system. You missed all three attempts.

The root password is correct and I can use the command su on terminal.

**Comment by prdm0** [comment]
I need more details of your distribution, system users, setting user permissions, etc. With this simple question it is not possible to imagine what is happening. Also note that in more than 10,000 downloads, this is the first time that I have been asked about it. There may be some configuration on your user that is not allowing the program to proceed with tasks.
