### ISSUE TITLE
compilation in the userspace

### ISSUE THREAD

**Issue by lolow** [prdm0/ropenblas#29]
I have a specific version of R that I use from the userspace, could ropenblas be installed and linked to the R installation in my userspace. 
I see that you install openblas in /opt, could it be possible to enter another folder located in my HOME?
thanks!

**Comment by prdm0** [comment]
Hello @lolow, I will include this in future versions of `ropenblas`. It is necessary for the package to automatically understand the permission of the directory and if it does not need the ROOT password, it will be installed without a password request in the `$HOME` directory or any other that is specified.

**Comment by prdm0** [comment]
Dear @lolow,

If possible, I implemented your request. It is being tested on the branch named "local". To test, run:

`remotes::install_github(repo = "prdm0/ropenblas", ref = "local", force = TRUE)`
