### ISSUE TITLE
Erro ropenblas apos instalacao do R.4.1.0

### ISSUE THREAD

**Issue by fmcron** [prdm0/ropenblas#30]
Atualizei o R para a ultima versao a 4.1.0. Ao tentar linkar a ropenblas para a ultima versao, uma mensagem de erro aparece, informando que a minha senha de root esta incorreta. 

Pela mensagem, parece que o comando que envia a senha para o SO, nao esta aceitando caracteres especiais, pois esta retornando ")" como erro, o que na verdade e parte da minha senha de root.

Eu utilizo NVIM + Nvim-R-plugin como editor de codigo R, mas tentei no RStudio e o erro e o mesmo. Meu SO e Linux MInt 20.

Poderia auxiliar com esse erro?

> ropenblas::ropenblas(x="4.1.0")
Enter your ROOT OS password (attempt 1 of 3): ***********
sh: 1: Syntax error: ")" unexpected
Enter your ROOT OS password (attempt 2 of 3): ***********
sh: 1: Syntax error: ")" unexpected
Enter your ROOT OS password (attempt 3 of 3): ***********
sh: 1: Syntax error: ")" unexpected
Error in sudo_key() :
Sorry. Apparently you don't is the administrator of the operating system. You missed all three attempts

Atenciosamente
--

              Fábio Mathias Corrêa

**Comment by prdm0** [comment]
@fmcron , irei olhar atentamente para esse problema nas futuras versões do pacote. Obrigado pela Issue.

**Comment by prdm0** [comment]
@fmcron atualmente esse problema não existe mais. O pacote **ropenblas** agora admite caracteres especiais na senha do root. Também há um branch de nome `local` que permite a instalação local do R e da biblioteca OpenBLAS. Para experimentar, basta fazer:

```remotes::install_github("prdm0/ropenblas", ref = "local", force = TRUE)``` 

Portanto, irei fechar essa issue.
