### ISSUE TITLE
How can I use it for Windows System

### ISSUE THREAD

**Issue by vikram-rawat** [prdm0/ropenblas#32]
It's a wonderful package in the right direction as well. Thanks for it. I Just wanted to know currently it doesn't support windows but Is there any perticular steps by which I can use it on Windows ??? I am a windows user and I would like to use it on windows...

**Comment by aadler** [comment]
See https://www.avrahamadler.com/2022/01/17/building-r-42-with-openblas-windows/

**Comment by prdm0** [comment]
Dear, at some point I will look into this. @aadler if you're interested in contributing code, you're welcome. I will certainly look very carefully at any pull requests related to this. 

I think that initially it would be interesting to create an independent function, equivalent to `rcompiler` or `ropenblas`, to deal only with the Windows system. If something consistent is proposed in a pull request, these routines can gradually migrate the official functions of the package.

Best regards.
