### ISSUE TITLE
Switching between openblas and the original one

### ISSUE THREAD

**Issue by oujenhsiang** [prdm0/ropenblas#33]
Is there a way to easily switch between openblas and the original blas?

**Comment by prdm0** [comment]
Dear @oujenhsiang , it is currently not possible to go back using the package. However, just install BLAS again in the operating system and the link to OpenBLAS is eliminated. I intend to give this possibility in future versions.

Currently the package allows switching between versions of R and linking any version of OpenBLAS to R, and it is also possible to switch between versions of OpenBLAS. The package does not allow you to go to any version of BLAS or switch between them.

**Comment by prdm0** [comment]
In my case I use Arch Linux. If I eventually need to go back to BLAS, it never occurred to me, I just do it on the system: `sudo pacman -S blas`.

I will look into the possibility of allowing the same thing for BLAS.

**Comment by oujenhsiang** [comment]
Thanks! Just being curious if this switching function is in this package. Doing so manually is just fine. Love your job. This makes my work easier!
